---
- name: Create caddy_data volume
  community.docker.docker_volume:
    name: caddy_data
    state: present

- name: Create caddy_config volume
  community.docker.docker_volume:
    name: caddy_config
    state: present

- name: Generate /etc/caddy/conf.d
  become: true
  ansible.builtin.file:
    path: /etc/caddy/conf.d
    state: directory
    mode: '0775'

- name: Generate /etc/caddy/Caddyfile
  become: true
  ansible.builtin.template:
    src: Caddyfile.j2
    dest: /etc/caddy/Caddyfile
    mode: '0775'

- name: Create caddy_net network
  community.docker.docker_network:
    name: caddy_net

- name: Make caddy dir
  ansible.builtin.file:
    path: ~/caddy
    state: directory
    mode: '0755'

- name: Copy file with owner and permissions
  ansible.builtin.copy:
    src: Dockerfile
    dest: ~/caddy/Dockerfile
    mode: '0644'

- name: Build image and with build args
  community.docker.docker_image:
    name: caddy-ut:latest
    build:
      path: ~/caddy
    source: build

- name: Create caddy container
  community.docker.docker_container:
    name: caddy
    image: caddy-ut:latest
    restart: true
    recreate: true
    comparisons:
      networks: strict
    restart_policy: always
    networks:
      - name: caddy_net
    pull: false
    capabilities:
      - NET_ADMIN
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - /etc/caddy:/etc/caddy
    env:
      ACME_AGREE: "true"
    ports:
      - "127.0.0.1:2019:2019"
      - "{{ service_ip | default(ip) }}:443:443"
      - "{{ service_ip | default(ip) }}:80:80"
      - "[{{ service_ip6 }}]:443:443"
      - "[{{ service_ip6 }}]:80:80"
