- name: uncletopia-web_db volume
  docker_volume:
    name: uncletopia-web_db
    state: present
    
- name: uncletopia-web-postgres container
  docker_container:
    name: uncletopia-web-postgres
    image: postgis/postgis:latest
    restart: yes
    recreate: yes
    pull: yes
    volumes:
      - uncletopia-web_db:/var/lib/postgresql/data
    env:
      POSTGRES_DB: "uncletopia-web"
      POSTGRES_PASSWORD: "uncletopia-web"
      POSTGRES_USER: "uncletopia-web"
    ports:
      - 127.0.0.1:5433:5432

- name: Generate /etc/uncletopia-web.yml
  become: yes
  template:
    src: uncletopia-web.yml.j2
    dest: /etc/uncletopia-web.yml
    mode: 0770

- name: uncletopia-web container
  docker_container:
    name: uncletopia-web
    image: leighmacdonald/uncletopia-web:latest
    restart: yes
    recreate: yes
    pull: yes
    links:
      - uncletopia-web-postgres
    restart_policy: unless-stopped
    volumes:
      - /etc/uncletopia-web.yml:/app/config.yml

- name: Join gbans network
  community.docker.docker_network:
    name: caddy_net
    connected:
      - uncletopia-web
    appends: yes
