---
- name: Firewall Setup
  hosts: all
  become: true
  tasks:
    - block:
        - name: Install UFW
          ansible.builtin.apt:
            name: ufw
            state: present

        - name: Reset UFW
          community.general.ufw:
            state: reset

        - name: Allow outgoing traffic
          community.general.ufw:
            default: allow
            direction: outgoing

        - name: Deny incoming
          community.general.ufw:
            default: deny
            direction: incoming

        - name: Allow Game Port
          community.general.ufw:
            rule: allow
            port: "{{ srcds_base_port + (loop0 * 10) }}"
            proto: udp
            comment: srcds-game
            from_ip: 0.0.0.0/0
          loop: "{{ services }}"
          loop_control:
            index_var: loop0
          when: ansible_distribution == 'Ubuntu'

        - name: Allow RCON Port
          community.general.ufw:
            rule: allow
            port: "{{ srcds_base_port + (loop0 * 10) }}"
            proto: tcp
            comment: srcds-rcon
            src: "{{ vpn_mask }}"
          loop: "{{ services }}"
          loop_control:
            index_var: loop0
          when: ansible_distribution == 'Ubuntu'

        - name: Allow SourceTV
          community.general.ufw:
            rule: allow
            port: "{{ srcds_base_port + (loop0 * 10) + 1 }}"
            proto: udp
            comment: srcds-stv
            from_ip: 0.0.0.0/0
          loop: "{{ services }}"
          loop_control:
            index_var: loop0
          when: ansible_distribution == 'Ubuntu'

        - name: Allow SRCDS Logs
          community.general.ufw:
            rule: allow
            port: "{{ srcds_log_port }}"
            proto: udp
            comment: srcds-stv
            from_ip: 0.0.0.0/0
          when: ansible_distribution == 'Ubuntu'

        - name: Allow SRCDS Postgres
          community.general.ufw:
            rule: allow
            port: 5432
            proto: tcp
            comment: srcds-postgres-client
            src: "{{ vpn_mask }}"
          when: ansible_distribution == 'Ubuntu' and inventory_hostname == metrics_hostname

        - name: Allow HTTP
          community.general.ufw:
            rule: allow
            port: "{{ item }}"
            proto: tcp
            comment: http
            dest: "{{ http_ip }}"
          loop:
            - 80
            - 443
          when: ansible_distribution == 'Ubuntu' and inventory_hostname == metrics_hostname

        - name: Allow HTTP (QUIC)
          community.general.ufw:
            rule: allow
            port: 443
            proto: udp
            comment: http-quic
            dest: "{{ http_ip }}"
          when: ansible_distribution == 'Ubuntu' and inventory_hostname == metrics_hostname

        - name: Allow node_exporter
          community.general.ufw:
            rule: allow
            port: 9100
            proto: tcp
            comment: node_exporter
            src: "{{ vpn_mask }}"

      always:
        - name: Grant ssh access
          community.general.ufw:
            rule: allow
            direction: in
            port: "22"
            proto: tcp
            from_ip: "{{ item }}"
          loop: "{{ ssh_allowed_hosts }}"

        - name: Enable Firewall
          community.general.ufw:
            state: enabled
