all:
  children:
    dev:
      hosts:
        localhost:

    metrics:
      hosts:
        mtl-1.ca.uncletopia.com:
          ansible_python_interpreter: python3

    tf2:
      children:
        dev:
          hosts:
            localhost:
              ansible_python_interpreter: python3
        test:
          hosts:
            test-1.ca.uncletopia.com:
              ansible_python_interpreter: python3
            test-2.ca.uncletopia.com:
              ansible_python_interpreter: python3
        na:
          children:
            nae:
              hosts:
                atl-1.us.uncletopia.com:
                  ansible_python_interpreter: python3
                mtl-1.ca.uncletopia.com:
                  ansible_python_interpreter: python3
                nyc-1.us.uncletopia.com:
                  ansible_python_interpreter: python3
                mia-1.us.uncletopia.com:
                  ansible_python_interpreter: python3
            nac:
              hosts:
                chi-1.us.uncletopia.com:
                  ansible_python_interpreter: python3
                chi-2.us.uncletopia.com:
                  ansible_python_interpreter: python3
                dal-1.us.uncletopia.com:
                  ansible_python_interpreter: python3
            naw:
              hosts:
                lax-1.us.uncletopia.com:
                  ansible_python_interpreter: python3
                sea-1.us.uncletopia.com:
                  ansible_python_interpreter: python3
                sfo-1.us.uncletopia.com:
                  ansible_python_interpreter: python3
        eu:
          hosts:
            lon-1.uk.uncletopia.com:
              ansible_python_interpreter: python3
            frk-1.de.uncletopia.com:
              ansible_python_interpreter: python3

        apac:
          children:
            sa:
              hosts:
                sao-1.br.uncletopia.com:
                  ansible_python_interpreter: python3
                sao-2.br.uncletopia.com:
                  ansible_python_interpreter: python3
            asia:
              hosts:
                hgk-1.hk.uncletopia.com:
                  ansible_python_interpreter: python3
                sgp-1.sg.uncletopia.com:
                  ansible_python_interpreter: python3
            aus:
              hosts:
                syd-1.au.uncletopia.com:
                  ansible_python_interpreter: python3
                syd-2.au.uncletopia.com:
                  ansible_python_interpreter: python3
