---
- name: Add Users
  import_playbook: playbooks/adduser.yml

- name: System Settings
  import_playbook: playbooks/system.yml

- name: Web
  import_playbook: playbooks/web.yml

- name: SRCDS
  import_playbook: playbooks/srcds.yml
