---
- name: System Setup
  hosts: all
  become: true
  tasks:
    - name: Set a hostname
      ansible.builtin.hostname:
        name: "{{ inventory_hostname }}"

    - name: Set timezone
      community.general.timezone:
        name: "{{ timezone }}"

    - name: Check if i386 is enabled
      ansible.builtin.shell: dpkg --print-foreign-architectures | grep i386 # noqa risky-shell-pipe
      register: result_i386_check
      changed_when: result_i386_check.rc == 1
      failed_when: result_i386_check.rc > 1
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

    - name: Add a PPA repository
      ansible.builtin.apt_repository:
        repo: "ppa:damentz/liquorix" # PPA URL
        state: present
        update_cache: true
        filename: "zen-repo"

    - name: Configure cpufrequtils
      become: true
      ansible.builtin.copy:
        dest: "/etc/default/cpufrequtils"
        mode: "0755"
        content: |
          GOVERNOR="performance"

    - name: Download docker gpg key
      become: true
      become_user: root
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add specified repository into sources list
      become: true
      become_user: root
      ansible.builtin.apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Enable i386 architecture # noqa no-changed-when
      ansible.builtin.command: dpkg --add-architecture i386
      when: result_i386_check.rc == 1

    - name: Install gpg & dd dependencies
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 0
        state: present
        pkg:
          - linux-image-liquorix-amd64
          - linux-headers-liquorix-amd64
          - unzip
          - gpg
          - cpufrequtils
          - python3-netaddr
          - wget
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - python3-docker
          - libc6:i386
          - lib32stdc++6
          - docker-buildx-plugin
          - rsync
          - cron

    - name: Create rcon directory if it does not exist
      ansible.builtin.file:
        path: ~/rcon
        state: directory
        mode: "0755"

    - name: Reload systemd daemon
      become: true
      ansible.builtin.systemd:
        daemon_reload: true

    - name: Add docker group to user
      become: true
      ansible.builtin.user:
        name: tf2server
        groups: docker
        append: true

    - name: Disable irqbalance # noqa: ignore-errors
      become: true
      ignore_errors: true
      ansible.builtin.systemd:
        name: irqbalance
        state: stopped
        masked: true
        enabled: false

    # ondemand service will force ondemand
    - name: Disable ondemand # noqa ignore-errors
      become: true
      ignore_errors: true
      ansible.builtin.systemd:
        name: ondemand
        state: stopped
        masked: true
        enabled: false

    - name: Enable docker service
      become: true
      ansible.builtin.systemd:
        name: docker
        state: started
        enabled: true

    - name: Create node_exporter container
      community.docker.docker_container:
        name: node_exporter
        image: prom/node-exporter:latest
        restart_policy: unless-stopped
        restart: true
        pull: true
        volumes:
          - "/:/host:ro,rslave"
        command:
          - "--path.rootfs=/host"
        ports:
          - "{{ vpn_ip[inventory_hostname] }}:9100:9100"
      tags:
        - metrics-client
        - node_exporter

    - name: Allow node_exporter firewall
      become: true
      community.general.ufw:
        interface_in: "tailscale0"
        rule: allow
        port: "9100"
        proto: tcp
