---
- name: Create caddy data volume
  community.docker.docker_volume:
    name: "{{ caddy_data_volume_name }}"
    state: present

- name: Create caddy config volume
  community.docker.docker_volume:
    name: "{{ caddy_config_volume_name }}"
    state: present

- name: Ensure caddy configuration directory exists
  become: true
  ansible.builtin.file:
    path: "{{ caddy_config_dir }}"
    state: directory
    mode: "0775"

- name: Deploy caddy configuration file
  become: true
  ansible.builtin.template:
    src: Caddyfile.j2
    dest: "{{ caddy_config_file }}"
    mode: "0775"

- name: Create caddy network
  community.docker.docker_network:
    name: "{{ caddy_network_name }}"

- name: Ensure caddy user directory exists
  ansible.builtin.file:
    path: "{{ caddy_user_dir }}"
    state: directory
    mode: "0755"

- name: Copy Dockerfile to caddy directory
  ansible.builtin.copy:
    src: Dockerfile
    dest: "{{ caddy_dockerfile_dest }}"
    mode: "0644"

- name: Build caddy docker image
  community.docker.docker_image:
    name: "{{ caddy_image_name }}"
    build:
      path: "{{ caddy_user_dir }}"
    source: build

- name: Deploy caddy container
  community.docker.docker_container:
    name: caddy
    image: "{{ caddy_image_name }}"
    restart: true
    recreate: true
    comparisons:
      networks: strict
    restart_policy: always
    networks:
      - name: "{{ caddy_network_name }}"
    pull: false
    capabilities:
      - NET_ADMIN
    volumes:
      - "{{ caddy_data_volume_name }}:/data"
      - "{{ caddy_config_volume_name }}:/config"
      - "/etc/caddy:/etc/caddy"
    env:
      ACME_AGREE: "true"
    ports:
      - "127.0.0.1:2019:2019"
      - "{{ (caddy_service_ip | default(caddy_ip)) }}:443:443"
      - "{{ (caddy_service_ip | default(caddy_ip)) }}:80:80"
      - "[{{ caddy_service_ip6 }}]:443:443"
      - "[{{ caddy_service_ip6 }}]:80:80"
