---
sourcemod_sm_download: "https://github.com/alliedmodders/sourcemod/releases/download/1.13.0.7441/sourcemod-1.13.0-git7441-linux.tar.gz"
sourcemod_metamod_download: "https://github.com/alliedmodders/metamod-source/releases/download/1.12.0.1225/mmsource-1.12.0-git1225-linux.tar.gz"
sourcemod_srcds_user: "tf2server"
sourcemod_srcds_homedir: "/home/tf2server"
sourcemod_plugins_disabled: []
sourcemod_extensions_disabled: []
sourcemod_sentry_dsn: ""
sourcemod_discord:
  stac_webhook: ""
  crash_webhook: ""
sourcemod_pve:
  bot_count: "{{ item.bot_count | default(20) }}"
  human_count: "{{ item.human_count | default(12) }}"
  # xmas cosmetics
  # cosmetic_1: 30539
  # cosmetic_2: 666
  # cosmetic_3: 30172
  bot_attrs:
    metal regen: 500
    maxammo metal increased: 2.5
    # 125 + 60 = 185
    max health additive bonus: 60
    mod teleporter cost: 20
  names:
    - Uncle Frames
    - Uncle Brain
    - Uncle Lane
    - Uncle Migraine
    - Uncle Grain
    - Uncle Slain
    - Uncle Crane
    - Uncle Strain
    - Uncle Vain
    - Uncle Train
    - Uncle Stain
    - Uncle Bens
    - Uncle Insane
    - Uncle Buck
    - Uncle Leo
    - Uncle Fester
    - Uncle Pain
    - Uncle Fred
    - Uncle Whole Grain
    - Uncle Oscar
    - Uncle Phil
    - Uncle Jesse
    - Uncle Lame
    - Uncle Flame
    - Uncle Same
    - Uncle Cocaine
    - Uncle Buster
    - Uncle Frank
    - Uncle Funkle
    - Uncle Remus
    - Uncle Lo Mein
    - Uncle Bobby
    - Uncle Joe
    - Uncle Junior
    - Uncle Elroy
    - Uncle Owen
    - Uncle Dursley
    - Uncle Al
    - Uncle Aeroplane
    - Uncle G-Man
    - Uncle Red Shirt
    - Uncle Lazer
    - Uncle Drain
    - Uncle Rain
    - Uncle Feign
    - Uncle Arcane
    - Uncle Propane
    - Uncle Claim
    - Uncle Plain
    - Uncle Ukraine
    - Uncle Explain
    - Uncle Strange
    - Uncle Lil Wayne

sourcemod_items:
  # https://wiki.alliedmods.net/Team_fortress_2_item_definition_indexes
  dodgeball: |
    "custom_weapons_v3"
    {
     	"*"
     	{
        # 356 -> 0 airblast_disabled
    		"594"
    		{
    		  "1" "356 ; 0"
          "preserve-attributes" "1"
        }
      }
    }
