---
sourcemod_sm_download: "https://sm.alliedmods.net/smdrop/1.13/sourcemod-1.13.0-git7176-linux.tar.gz"
sourcemod_metamod_download: "https://mms.alliedmods.net/mmsdrop/1.12/mmsource-1.12.0-git1194-linux.tar.gz"
sourcemod_srcds_user: "tf2server"
sourcemod_srcds_homedir: "/home/tf2server"
sourcemod_plugins_disabled: []
sourcemod_extensions_disabled: []
