---
# sourcemod_sm_download: "https://github.com/alliedmodders/sourcemod/releases/download/1.13.0.7453/sourcemod-1.13.0-git7453-linux.tar.gz"
# sourcemod_metamod_download: "https://github.com/alliedmodders/metamod-source/releases/download/2.0.0.1411/mmsource-2.0.0-git1411-linux.tar.gz"
sourcemod_sm_download: "https://github.com/alliedmodders/sourcemod/releases/download/1.12.0.7253/sourcemod-1.12.0-git7253-linux.tar.gz"
sourcemod_metamod_download: "https://github.com/alliedmodders/metamod-source/releases/download/2.0.0.1411/mmsource-2.0.0-git1411-linux.tar.gz"
# sourcemod_sm_download: "https://github.com/alliedmodders/sourcemod/releases/download/1.13.0.7456/sourcemod-1.13.0-git7456-linux.tar.gz"
# sourcemod_metamod_download: "https://github.com/alliedmodders/metamod-source/releases/download/2.0.0.1411/mmsource-2.0.0-git1411-linux.tar.gz"
sourcemod_srcds_user: "tf2server"
sourcemod_srcds_homedir: "/home/tf2server"
sourcemod_plugins_disabled: []
sourcemod_extensions_disabled: []
sourcemod_sentry_dsn: ""

sourcemod_items:
  # https://wiki.alliedmods.net/Team_fortress_2_item_definition_indexes
  dodgeball: |
    "custom_weapons_v3"
    {
     	"*"
     	{
        # 356 -> 0 airblast_disabled
    		"594"
    		{
    		  "1" "356 ; 0"
          "preserve-attributes" "1"
        }
      }
    }
