---
galaxy_info:
  author: uncletopia
  description: Uncledane web interface
  company: uncletopia.com
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: Ubuntu
      release:
        - focal
    - name: Debian
      release:
        - bookworm
  galaxy_tags:
    - uncledane
    - web

dependencies: []
