---
galaxy_info:
  author: uncletopia
  description: Caddy reverse proxy with Docker
  company: uncletopia.com
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: Ubuntu
      release:
        - focal
    - name: Debian
      release:
        - bookworm
  galaxy_tags:
    - caddy
    - proxy
    - docker

dependencies: []
