---

- name: Generate /etc/bdapi.yml
  become: true
  ansible.builtin.template:
    src: bdapi.yml.j2
    dest: /etc/bdapi.yml
    mode: 0775

- name: Generate /etc/bdapi.key
  become: true
  ansible.builtin.copy:
    content: "{{ bdapi_private_key }}"
    dest: /etc/bdapi.key
    mode: 0600
    owner: tf2server
    group: tf2

- name: bdapi_cache_data volume
  docker_volume:
    name: bdapi_cache_data
    state: present

- name: Create bdapi_postgres_data volume
  docker_volume:
    name: bdapi_db
    state: present

- name: Create bdapi-postgres container
  docker_container:
    name: bdapi-postgres
    image: postgres:15-bullseye
    restart: true
    recreate: true
    pull: true
    purge_networks: true
    restart_policy: unless-stopped
    volumes:
      - bdapi_db:/var/lib/postgresql/data
    networks:
      - name: caddy_net
    env:
      POSTGRES_DB: bdapi
      POSTGRES_PASSWORD: bdapi
      POSTGRES_USER: bdapi
    ports:
      - 127.0.0.1:5445:5432
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"

- name: bd-api-service
  docker_container:
    name: bd-api-service
    image: ghcr.io/leighmacdonald/bd-api:v1.0.5
    restart: true
    recreate: true
    pull: true
    restart_policy: always
    state: started
    networks:
      - name: caddy_net
    volumes:
      - bdapi_cache_data:/app/.cache
      - /etc/bdapi.yml:/app/bdapi.yml
      - /etc/bdapi.key:/app/private.key
    ports:
      - 127.0.0.1:8888:8888
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"

