---

- name: Create gbans_cache_data volume
  community.docker.docker_volume:
    name: gbans_cache_data
    state: present

- name: Create gbans assets volume
  community.docker.docker_volume:
    name: gbans_assets
    state: present

- name: Generate /etc/gbans.yml
  become: true
  ansible.builtin.template:
    src: gbans.yml.j2
    dest: /etc/gbans.yml
    mode: "0770"

- name: Create gbans-service
  community.docker.docker_container:
    name: gbans-service
    image: "{{ gbans_web.image }}"
    restart: true
    recreate: true
    pull: true
    restart_policy: always
    state: started
    comparisons:
      networks: strict
    networks:
      - name: caddy_net
    volumes:
      - /home/tf2server/.ssh/ut_stv:/app/ut_stv
      - gbans_assets:/app/assets
      - gbans_cache_data:/app/.cache
      - /etc/gbans.yml:/app/gbans.yml
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"
    env:
      GBANS_DATABASE_DSN: "{{ gbans_web.database_dsn }}"
      GBANS_GENERAL_STEAM_KEY: "{{ steam_key }}"
    ports:
      - 127.0.0.1:6006:6006
      - 27715:27715/udp

- name: Create gbans-river
  community.docker.docker_container:
    name: gbans-river
    image: ghcr.io/riverqueue/riverui:latest
    restart: true
    recreate: true
    pull: true
    restart_policy: always
    state: started
    networks:
      - name: caddy_net
    env:
      DATABASE_URL: "{{ gbans_web.database_dsn }}"
    ports:
      - "{{ vpn_hosts[inventory_hostname].ip }}:8081:8080"
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"

- name: Create srcds-log-fw
  become: true
  community.general.ufw:
    interface_in: "wg0"
    rule: allow
    port: "27715"
    proto: udp

- name: Generate /gbans.conf
  ansible.builtin.template:
    src: gbans.conf.j2
    dest: gbans.conf
    mode: "0770"

- name: Copy caddy config
  community.docker.docker_container_copy_into:
    container: Caddy
    path: gbans.conf
    container_path: /etc/caddy/conf.d/gbans.conf
  notify:
    - restart caddy
