---
- name: Generate /etc/grafana.ini
  become: true
  ansible.builtin.template:
    src: grafana.ini.j2
    dest: /etc/grafana.ini
    mode: 0770
  tags:
    - grafana

- name: Create a directory if it does not exist
  become: true
  ansible.builtin.file:
    path: /etc/grafana/provisioning/datasources/
    state: directory
    mode: '0777'
  tags:
    - grafana

- name: Create a directory if it does not exist
  become: true
  ansible.builtin.file:
    path: /etc/grafana/provisioning/dashboards/
    state: directory
    mode: '0777'
  tags:
    - grafana

- name: Generate /etc/grafana_datasources.yml
  become: true
  ansible.builtin.template:
    src: datasources.yml.j2
    dest: /etc/grafana_datasources.yml
    mode: 0770
  tags:
    - grafana

- name: Generate /etc/grafana_dashboards.yml
  become: true
  ansible.builtin.template:
    src: dashboards.yml.j2
    dest: /etc/grafana_dashboards.yml
    mode: 0770
  tags:
    - grafana

- name: Copy dashboard sources
  become: true
  ansible.builtin.copy:
    src: "{{ role_path }}/files/"
    dest: /etc/grafana_dashboards
  tags:
    - grafana

- name: Create grafana_data volume
  docker_volume:
    name: grafana_data
    state: present
  tags:
    - grafana

- name: Create grafana_image_renderer container
  docker_container:
    name: grafana_image_renderer
    image: grafana/grafana-image-renderer:latest
    restart: true
    recreate: true
    restart_policy: unless-stopped
    networks:
      - name: caddy_net
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"
    pull: true
    ports:
      - 127.0.0.1:8081:8081
  tags:
    - grafana

- name: Create grafana container
  docker_container:
    name: grafana
    image: grafana/grafana-oss:latest-ubuntu
    restart: true
    recreate: true
    restart_policy: unless-stopped
    purge_networks: true
    networks:
      - name: caddy_net
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"
    pull: true
    volumes:
      - /etc/grafana.ini:/etc/grafana/grafana.ini
      - /etc/grafana_datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
      - /etc/grafana_dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
      - /etc/grafana_dashboards:/etc/grafana_dashboards
      - grafana_data:/var/lib/grafana
    ports:
      - 127.0.0.1:3000:3000
  tags:
    - grafana

