---

- name: node_exporter
  import_tasks: node_exporter.yml
  tags:
    - metrics-client

- name: minio
  import_tasks: minio.yml
  tags:
    - metrics-server

- name: prometheus
  import_tasks: prometheus.yml
  tags:
    - metrics-server

- name: promtail
  import_tasks: promtail.yml
  tags:
    - metrics-client

- name: loki
  import_tasks: loki.yml
  tags:
    - metrics-server

- name: tempo
  import_tasks: tempo.yml
  tags:
    - metrics-server

#- name: mimir
#  import_tasks: mimir.yml
#  tags:
#    - metrics-server

- name: grafana
  import_tasks: grafana.yml
  tags:
    - metrics-server
