---

- name: Create minio_data volume
  community.docker.docker_volume:
    name: minio_data
    state: present

- name: Create minio_data container
  community.docker.docker_container:
    name: minio
    image: minio/minio
    restart: true
    pull: true
    purge_networks: true
    restart_policy: unless-stopped
    recreate: true
    command: server /data --console-address ":{{ minio.port_webui }}"
    env:
      MINIO_ROOT_USER: "{{ minio.user | default('mimir') }}"
      MINIO_ROOT_PASSWORD: "{{ minio.password | default('mimirmimir') }}"
      MINIO_PROMETHEUS_AUTH_TYPE: "public"
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"
    networks:
      - name: caddy_net
    volumes:
      - minio_data:/data
    ports:
      - "127.0.0.1:{{ minio.port_webui }}:9001"
      - "{{ vpn_hosts[inventory_hostname].ip }}:{{ minio.port_webui }}:9001"
      - "127.0.0.1:{{ minio.port_api }}:9000"
      - "{{ vpn_hosts[inventory_hostname].ip }}:{{ minio.port_api }}:9000"
