---

- name: Create node_exporter container
  docker_container:
    name: node_exporter
    image: prom/node-exporter:latest
    restart_policy: unless-stopped
    restart: true
    pull: true
    volumes:
      - "/:/host:ro,rslave"
    command:
      - "--path.rootfs=/host"
    ports:
      - "{{ vpn_hosts[inventory_hostname].ip|default(ip) }}:9100:9100"
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"
  tags:
    - metrics-client
    - node_exporter
