---

- name: Create prometheus_data volume
  docker_volume:
    name: prometheus_data
    state: present
  tags:
    - metrics-server
    - prometheus

- name: Generate /etc/prometheus.yml
  become: true
  ansible.builtin.template:
    src: prometheus.yml.j2
    dest: /etc/prometheus.yml
    mode: 0775
  tags:
    - metrics-server
    - prometheus

- name: Create prometheus container
  docker_container:
    name: prometheus
    image: prom/prometheus:latest
    pull: true
    restart: true
    purge_networks: true
    restart_policy: unless-stopped
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      # required for tempo to directly write to prom
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
      # Agent mode disabled local disk storage. We send to mimir for long term storage
      # so this would be redundant.
      # - --enable-feature=agent
    recreate: true
    networks:
      - name: caddy_net
    volumes:
      - prometheus_data:/prometheus
      - /etc/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 127.0.0.1:9090:9090
      - "{{ vpn_hosts[metrics_hostname].ip|default(ip) }}:9090:9090"
  tags:
    - metrics-server
    - prometheus
