---


- name: Generate /etc/promtail.yml
  become: true
  ansible.builtin.template:
    src: promtail.yml.j2
    dest: /etc/promtail.yml
    mode: "0770"
  tags:
    - promtail
    - metrics-client

- name: Create promtail container
  community.docker.docker_container:
    name: promtail
    image: grafana/promtail:latest
    restart: true
    pull: true
    restart_policy: unless-stopped
    recreate: true
    command: ["-config.file=/etc/promtail.yml"]
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"
    networks:
      - name: caddy_net
    volumes:
      - /etc/promtail.yml:/etc/promtail.yml
      - /etc/machine-id:/etc/machine-id
      - /var/log/journal/:/var/log/journal/
      - /run/log/journal/:/run/log/journal/
      - /var/run/docker.sock:/var/run/docker.sock
      - tempo_data:/tmp/tempo
    ports:
      - "127.0.0.1:9080:9080"
      - "{{ vpn_hosts[inventory_hostname].ip | default(ip) }}:9080:9080"
  tags:
    - promtail
    - metrics-client
