#!/usr/bin/env python3
from genericpath import isdir
from os import listdir
import subprocess
import sys


class ValidationError(Exception):
    pass


def repo_dir():
    resp = subprocess.run(["git", "rev-parse", "--show-toplevel"], stdout=subprocess.PIPE)
    return resp.stdout.decode('utf-8').rstrip()


ROOT = repo_dir()


def ensure_ansible_lint():
    print("Checking ansible-lint")
    subprocess.check_call(["ansible-lint"])


def format_sp():
    print("Formatting sp")
    subprocess.check_call(["make", "format"])


def main():
    ret_val = 255
    try:
        # format_sp()
        ensure_ansible_lint()
    except ValidationError as err:
        print("[ERROR] {}".format(err))
        ret_val = 1
    except Exception as err:
        print("[Exc] {}".format(err))
    else:
        ret_val = 0
    finally:
        return ret_val


if __name__ == "__main__":
    sys.exit(main())
