- name: wget linuxgsm
  get_url:
    url: https://linuxgsm.sh
    dest: ~/linuxgsm.sh
    mode: 0777

- name: linuxgsm tf2server
  command: ~/linuxgsm.sh tf2server
  args:
    creates: tf2server

- name: tf2server install
  command: ./tf2server ai
  args:
    creates: serverfiles/srcds_run

