- hosts: all
  # roles:
    #  ansible-galaxy install cloudalchemy.node_exporter
    # - cloudalchemy.node_exporter
  tasks:
    - name: node-exporter-fw
      become: true
      ufw:
        rule: allow
        port: "9100"
        proto: tcp
