---
- name: Create portainer_data volume
  docker_volume:
    name: portainer_data
    state: present

- name: Create portainer container
  docker_container:
    name: portainer
    image: portainer/portainer-ce:latest
    restart: true
    recreate: true
    purge_networks: true
    pull: true
    networks:
      - name: caddy_net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - 127.0.0.1:9000:9000
