---
- name: Create prometheus_data volume
  docker_volume:
    name: prometheus_data
    state: present

- name: Generate /etc/prometheus.yml
  become: true
  ansible.builtin.template:
    src: prometheus.yml.j2
    dest: /etc/prometheus.yml
    mode: 0775

- name: Create prometheus container
  docker_container:
    name: prometheus
    image: prom/prometheus:latest
    restart: true
    purge_networks: true
    recreate: true
    networks:
      - name: caddy_net
    volumes:
      - prometheus_data:/prometheus
      - /etc/prometheus.yml:/etc/prometheus/prometheus.yml
    env:
      CLOUDFLARE_EMAIL: "{{ caddy.cloudflare.email }}"
      CLOUDFLARE_API_TOKEN: "{{ caddy.cloudflare.api_key }}"
      ACME_AGREE: "true"
    ports:
      - 127.0.0.1:9090:9090
