
- name: metrics network
  community.docker.docker_network:
    name: metrics_net

- name: prometheus_data volume
  docker_volume:
    name: prometheus_data
    state: present

- name: Generate /etc/prometheus.yml
  become: yes
  template:
    src: prometheus.yml.j2
    dest: /etc/prometheus.yml
    mode: 0775

- name: prometheus
  docker_container:
    name: prometheus
    image: prom/prometheus:latest
    restart: yes
    recreate: yes
    volumes:
      - prometheus_data:/prometheus
      - /etc/prometheus.yml:/etc/prometheus/prometheus.yml
    env:
      CLOUDFLARE_EMAIL: "{{ caddy.cloudflare.email }}"
      CLOUDFLARE_API_TOKEN: "{{ caddy.cloudflare.api_key }}"
      ACME_AGREE: "true"
    ports:
      - 127.0.0.1:9090:9090

- name: Join metrics network
  community.docker.docker_network:
    name: metrics_net
    connected:
      - prometheus
    appends: yes

- name: Join metrics network
  community.docker.docker_network:
    name: gbans_net
    connected:
      - prometheus
    appends: yes

- name: Reload networks
  docker_container:
    name: prometheus
    restart: yes
