name: Ansible Lint # feel free to pick your own name

on: [push, pull_request]

jobs:
  lint:
    name: Ansible Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Run ansible-lint
        uses: ansible/ansible-lint@main
        #        # optional (see below):
        with:
          args: "--exclude sm_plugins watcher"
          setup_python: "true"
          working_directory: ""
          requirements_file: ""

  sourcemod:
    name: Build Plugins
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Compile SourceMod plugins
        run: nix develop -c scripts/compile-sp-plugin.sh
