name: Ansible Lint  # feel free to pick your own name

on: [push, pull_request]

jobs:
  lint:
    name: Ansible Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run ansible-lint
        uses: ansible/ansible-lint@main
#        # optional (see below):
        with:
          args: "--exclude sm_plugins watcher"
          setup_python: "true"
          working_directory: ""
          requirements_file: ""

  sourcemod:
    name: Build Plugins
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup SourcePawn Compiler
        uses: rumblefrog/setup-sp@master
        with:
          version: "1.12.x"

      - name: Ensure plugin builds
        working-directory: ./playbooks/roles/sourcemod/files/addons/sourcemod/scripting
        run: |
          for file in *.sp; do
            f=${file%.*}
            echo -e "\nCompiling $file... to ../plugins/${f}.smx"
            spcomp -E -w234 -O2 -v2 -i include $file -o ../plugins/$f.smx
          done
          
          echo "===OUT FILES==="
          ls
          echo version = ${{ steps.setup_sp.outputs.plugin-version }}