name: Ansible Lint  # feel free to pick your own name

on: [push, pull_request]

jobs:
  lint:
    name: Ansible Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run ansible-lint
        uses: ansible/ansible-lint@main
#        # optional (see below):
#        with:
#          args: ""
#          setup_python: "true"
#          working_directory: ""
#          requirements_file: ""

  sourcemod:
    name: Build Plugins
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup SourcePawn Compiler
        uses: rumblefrog/setup-sp@master
        with:
          version: "1.12.x"

      - name: Ensure plugin builds
        working-directory: ./sourcemod/scripting
        run: ./compile.sh